@host = http://localhost:3000

### singup new user
POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "12dqw32",
  "name": "Jon Doe",
  "expertise": "Developer",
  "dob": "1995-06-14",
  "gender": "male",
  "country": "SA",
  "avatar": "/image.png",
  "mobile": "+971232143243",
  "bio": "This is my bio"
}