@host = http://localhost:3000

### singup new user
POST {{host}}/user/signup
Content-Type: application/json

{
  "email": "test12334@test.com",
  "password": "12dqw32",
  "name": "Jon Doe",
  "expertise": "Developer",
  "dob": "1995-06-14",
  "gender": "male",
  "country": "SA",
  "avatar": "/image.png",
  "mobile": "+971232143243",
  "bio": "This is my bio"
}

### get user profile
GET {{host}}/profile/3c6731d4-8709-4dbf-83d4-9636e364095f


### update user email
PATCH {{host}}/user/update/email
Content-Type: application/json

{
    "password": "ss",
    "newEmail": "assdscsa@test.com"
}

### update user
PATCH {{host}}/user/update/info
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="user.png"
Content-Type: application/octet-stream

< ./user.png

--MyBoundary
Content-Disposition: form-data; name="name"

Abdel
--MyBoundary--