@host = http://localhost:3000

### singup new user
POST {{host}}/user/signup
Content-Type: application/json

{
  "email": "test12334@test.com",
  "password": "12dqw32",
  "name": "Jon Doe",
  "expertise": "Developer",
  "dob": "1995-06-14",
  "gender": "male",
  "country": "SA",
  "avatar": "/image.png",
  "mobile": "+971232143243",
  "bio": "This is my bio"
}

### get user profile
GET {{host}}/profile/testinguser

### update user email
PATCH {{host}}/user/update/email/4073d820-9233-4518-818c-54d753687aac
Content-Type: application/json

{
    "password": "ss",
    "newEmail": "assdscsa@test.com"
}


### update user
PATCH {{host}}/user/update/info/4073d820-9233-4518-818c-54d753687aac
Content-Type: application/json

{
    "slug": "asds"
}